apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://stackoverflow.com/questions/57594001/how-can-i-create-a-namespace-with-kustomize/57640208#57640208
# NOTE: THIS MUST MATCH THE VALUE IN argocd-app.yaml
namespace: supercash-aws-sae1-prdt-ppd-dev

namePrefix: supercash-
nameSuffix: -aws-sae1-prdt-ppd-dev

commonLabels:
  product: supercash
  cloud: aws
  region: sae1
  type: prdt
  segment: ppd
  env: dev

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: registry.gitlab.com/supercash/services/parkinglots-service
    newTag: a616e559-develop
