apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: supercash-
nameSuffix: -aws-sae1-prdt-ppd-dev

commonLabels:
  product: supercash
  cloud: aws
  region: sae1
  type: prdt
  segment: ppd
  env: dev

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: registry.gitlab.com/supercash/services/parkinglots-service
    newTag: a616e559-develop
