apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkinglot-service
spec:
  replicas: 1

  template:
    spec:
      # https://gitlab.com/supercash/platform/k8s/k8s-eks-setup/-/wikis/1.-Setup/Terraform-Cluster-Setup#design
      nodeSelector:
        super.cash-worker_group-name: servicesprd

      containers:
        - name: parkinglot-service

          # In order to support Horizontal Pod Autoscaler, we need to provide the amount of resources
          # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
          resources:
            requests:
              memory: 400Mi
              cpu: 500m
            limits:
              memory: 400Mi
              cpu: 500m
