apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: parkinglot-service
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: parkinglot-service
  targetCPUUtilizationPercentage: 75
