apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://stackoverflow.com/questions/57594001/how-can-i-create-a-namespace-with-kustomize/57640208#57640208
# NOTE: THIS MUST MATCH THE VALUE IN argocd-app.yaml
namespace: supercash-aws-sae1-prdt-prd-prd

namePrefix: supercash-
nameSuffix: -aws-sae1-prdt-prd-prd

commonLabels:
  env: prd
  segment: prd

patchesStrategicMerge:
- deployment-patch.yaml
- deployment-resources-patch.yaml

images:
- name: registry.gitlab.com/supercash/services/parkinglot-service
  newTag: ec751944-develop

resources:
- ../../base
- hpa.yaml
