apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://stackoverflow.com/questions/57594001/how-can-i-create-a-namespace-with-kustomize/57640208#57640208
# NOTE: THIS MUST MATCH THE VALUE IN argocd-app.yaml
namespace: supercash-aws-sae1-prdt-ppd-qal

namePrefix: supercash-
nameSuffix: -aws-sae1-prdt-ppd-qal

commonLabels:
  env: qal


patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: registry.gitlab.com/supercash/services/parkinglot-service
  newTag: 324f17af-bugfix-properly-calculate-ticket-grace-period
resources:
- ../../base
