apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkinglots-service
spec:
  template:
    spec:
      securityContext: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: parkinglots-service
      containers:
        - name: parkinglots-service
          image: registry.gitlab.com/supercash/services/parkinglots-service
          imagePullPolicy: Always
          ports:
            - name: service
              containerPort: 8082
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 60
            httpGet:
              path: /parkinglots/actuator/health
              port: 8082
