apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkinglots-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      nodeSelector:
        super.cash-worker_group-name: services
#      resources:
#        requests:
#          memory: "64Mi"
#          cpu: "250m"
#        limits:
#          memory: "128Mi"
#          cpu: "500m"
