apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkinglots-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: parkinglots-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: parkinglots-service
    spec:
      nodeSelector:
        super.cash-worker_group-name: services
      restartPolicy: Always
