apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-gitlab-container-registry.yaml
  - deployment-base.yaml
  - service.yaml

patchesStrategicMerge:
  - deployment-resources.yaml
