# $ docker login -u marcellodesales -p HF***FK registry.gitlab.com
# WARNING! Using --password via the CLI is insecure. Use --password-stdin.
# Login Succeeded
# -------------------- Same command to create secret
# $ kubectl create secret docker-registry gitlab-container-registry-secret --docker-server=registry.gitlab.com --docker-username=marcellodesales --docker-password=HF*****FK
# secret/gitlab-container-registry-secret created
apiVersion: v1
kind: Secret
metadata:
  name: parkinglots-service
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoibWFyY2VsbG9kZXNhbGVzIiwicGFzc3dvcmQiOiJIRl9yeURYelllZ3drYXhGV1g5SyIsImF1dGgiOiJiV0Z5WTJWc2JHOWtaWE5oYkdWek9raEdYM0o1UkZoNldXVm5kMnRoZUVaWFdEbEwifX19

