apiVersion: v1
kind: Service
metadata:
  name: parkinglots-service
  labels:
    app.super.cash/service: parkinglots-service
spec:
  type: ClusterIP
  ports:
  - name: service
    port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    app.super.cash/service: parkinglots-service
